-- Ejercicio 3
CREATE TABLESPACE TS_FINTECH 
    DATAFILE 'fintech.dbf' SIZE 10M AUTOEXTEND ON;

-- Ejercicio 4
CREATE PROFILE PERF_ADMINISTRATIVO LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    IDLE_TIME 5;
    
-- Ejercicio 5
CREATE PROFILE PERF_USUARIO LIMIT
    SESSIONS_PER_USER 4
    PASSWORD_LIFE_TIME 30;

-- Ejercicio 6
SHOW PARAMETER RESOURCE_LIMIT;

-- Ejercicio 7
CREATE ROLE R_ADMINISTRADOR_SUPER;
GRANT CREATE TABLE TO R_ADMINISTRADOR_SUPER;
GRANT CONNECT TO R_ADMINISTRADOR_SUPER;

-- Ejercicio 8
CREATE USER USUARIO1
    IDENTIFIED BY usuario  --password
    PROFILE PERF_ADMINISTRATIVO
    DEFAULT TABLESPACE TS_FINTECH
        QUOTA 1M ON TS_FINTECH;
GRANT R_ADMINISTRADOR_SUPER TO USUARIO1;

CREATE USER USUARIO2
    IDENTIFIED BY usuario  --password
    PROFILE PERF_ADMINISTRATIVO
    --SET ROLE R_ADMINISTRADOR_SUPER
    DEFAULT TABLESPACE TS_FINTECH
        QUOTA 1M ON TS_FINTECH;
GRANT R_ADMINISTRADOR_SUPER TO USUARIO2;
    
-- Ejercicio 10
CREATE OR REPLACE PROCEDURE USUARIO1.PR_INSERTA_TABLA2 (
                                P_CODIGO IN NUMBER) AS
 BEGIN
      INSERT INTO TABLA2 VALUES (P_CODIGO);
 END PR_INSERTA_TABLA2;
/ 

-- Ejercicio 11
-- No funciona porque USUARIO1 no tiene permisos de ejecución

-- Ejercicio 12
GRANT EXECUTE ON USUARIO1.PR_INSERTA_TABLA2 TO USUARIO2;

-- Ejercicio 13
-- Si funciona

-- Ejercicio 14


-- Ejercicio 15
CREATE OR REPLACE PROCEDURE USUARIO1.PR_INSERTA_TABLA2 (
                                P_CODIGO IN NUMBER) AS
 BEGIN
      execute immediate 'INSERT INTO TABLA2 VALUES ('||P_CODIGO||')';
 END PR_INSERTA_TABLA2;
/ 

-- Ejercicio 16
-- Sí funciona

-- Ejercicio 17
-- Sí funciona

-- Ejercicio 18
-- Desde USUARIO1 -> no funciona
 CREATE OR REPLACE PROCEDURE PR_CREA_TABLA (
  P_TABLA IN VARCHAR2, P_ATRIBUTO IN VARCHAR2) AS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE '||P_TABLA||'('||P_ATRIBUTO||' NUMBER(9))';
 END PR_CREA_TABLA;
/
-- Desde SYSTEM
 CREATE OR REPLACE PROCEDURE USUARIO1.PR_CREA_TABLA (
  P_TABLA IN VARCHAR2, P_ATRIBUTO IN VARCHAR2) AS
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE '||P_TABLA||'('||P_ATRIBUTO||' NUMBER(9))';
 END PR_CREA_TABLA;
/

-- Ejercicio 19
-- No funciona, al USUARIO1 le faltan permisos para ejecutar la instrucción
